export class States {

  public stateHash : Record<string, string> = { 'AL':  'Alabama',
  'AK': 'Alaska',
  'AZ': 'Arizona',
  'AR': 'Arkansas',
  'CA': 'California',
  'CO': 'Colorado',
  'CT': 'Connecticut',
  'DC': 'District Of Columbia',
  'DE': 'Delaware',
  'FL': 'Florida',
  'GA': 'Georgia',
  'HI': 'Hawaii',
  'ID': 'Idaho',
  'IL': 'Illinois',
  'IN': 'Indiana',
  'IA': 'Iowa',
  'KS': 'Kansas',
  'KY': 'Kentucky',
  'LA': 'Louisiana',
  'ME': 'Maine',
  'MD': 'Maryland',
  'MA': 'Massachusetts',
  'MI': 'Michigan',
  'MN': 'Minnesota',
  'MS': 'Mississippi',
  'MO': 'Missouri',
  'MT': 'Montana',
  'NE': 'Nebraska',
  'NV': 'Nevada',
  'NH': 'New Hampshire',
  'NJ': 'New Jersey',
  'NM': 'New Mexico',
  'NY': 'New York',
  'NC': 'North Carolina',
  'ND': 'North Dakota',
  'OH': 'Ohio',
  'OK': 'Oklahoma',
  'OR': 'Oregon',
  'PA': 'Pennsylvania',
  'RI': 'Rhode Island',
  'SC': 'South Carolina',
  'SD': 'South Dakota',
  'TN': 'Tennessee',
  'TX': 'Texas',
  'UT': 'Utah',
  'VT': 'Vermont',
  'VA': 'Virginia',
  'WA': 'Washington',
  'WV': 'West Virginia',
  'WI': 'Wisconsin',
  'WY': 'Wyoming', 
  'AB': 'Alberta, Canada',
  'BC': 'British Columbia, Canada',
  'MB': 'Manitoba, Canada',
   'NB': 'NEW BRUNSWICK,CAN',
   'NF': 'NEWFOUNDLAND,CAN', 'NS': 'NOVA SCOTIA,CAN','NT': 'NORTHWEST TERRITORY','ON': 'ONTARIO,CAN',
   'PE': 'PRINCE EDW ISLAND', 'PQ': 'PROV OF QUE,CAN', 'PR': 'Puerto Rico', 'QC': 'QC',
   'SA': 'SASKATCHEWAN,CAN', 'SK': 'Saskatoon (Canada)', 'VI': 'VIRGIN ISLANDS',
   'YT': 'Yukon (Canada)',
   'INTL': 'International'
  }
}